jenssegers/date

src/lang/th/date.php
However, in Thai, we do not use the first 3 letters for month and day abbreviations.
Instead, we have predefined abbreviations for months and days, like so:
```php
// month abbreviations
'jan' => 'ม.ค.',
'feb' => 'ก.พ.',
'mar' => 'มี.ค.',
'apr' => 'เม.ย.',
'may' => 'พ.ค.',
'jun' => 'มิ.ย.',
'jul' => 'ก.ค.',
'aug' => 'ส.ค.',
'sep' => 'ก.ย.',
'oct' => 'ต.ค.',
'nov' => 'พ.ย.',
'dec' => 'ธ.ค.',
// day abbr.
'mon' => 'จ.',
'tue' => 'อ.',
'wed' => 'พ.',
'thu' => 'พฤ.',
'fri' => 'ศ.',
'sat' => 'ส.',
'sun' => 'อา.',
```
And Thai uses Buddhist calender which equivalent to the Western Year + 543.
For example, 2014 (Western Year) = 2557 (Buddhist Year)
=> add Thai language file.

src/lang/zh/date.php
no space between every word in chinese, and word '之'  is unnecessary.
=> remove space and '之'

composer.json
Also update the least php requirement since phpunit requires `>= 5.3.3`.
Added `branch-alias` to let developers install the latest version with `3.0.*@dev` as version number.
=> Add version numbers to dependencies.

src/Lang/cs.php, src/Lang/sk.php
Fixed bug where using diffForHumans() with current time would result in following error:
```
Unable to choose a translation for "sekundou|[2,Inf]:count sekundami" with locale "cs" for value "0".
```
I guess that the same error is in Slovenian language file.
=> Fix bug for "0 seconds ago" in Czech and Slovak

src/Lang/sh.php, src/Lang/sr.php
There was a slight typo in Serbian localization, this fixes it.
Although Serbo-croatian is out of use, there still may be certain situations where people would want to use it. This commit adds Serbo-croatian localization.
=> Fixed typo in 'August' in Serbian; Added Serbo-croatian (sh.php) for backwards compatibility.

src/Lang/zh-CN.php
zh and zh-CN is really the same things, and OSes prefer zh-CN :)
=> fix zh-CN not exist issue, fix #149

README.md, src/Lang/ka.php, tests/TranslationKaTest.php, tests/TranslationTest.php
Added Georgian (ka) localization. Also included unit tests for this language. 
P.S. All tests passed and code style is PSR-2
=> Added Georgian (ka) localization

.travis.yml
Though, I'd actually prefer it to just be removed.
=> Moved self-update to before_install

src/Date.php, tests/TranslationTest.php
This pull request is based on issue #198 
Some languages (e.g. Russian) have different translations for month and day names (e,g, depending on the grammatical case). The previous implementation of the `translateTimeString($time)` method only worked on strings, not respecting the translation file syntax.
This implementation (hopefully) correctly parses these multiple translation options in a single translation string and produces a (where possible) fully translated output string.
I added a test case to illustrate this new behavior: the German example works in the old and new version of the method, the Russian example however, only works with the translation algorithm.
As far as I can tell, I (thanks to the help of StyleCI) corrected all coding style which are due to this PR.
Please let me …
=> Added functionality to translate a pluralized string

src/Date.php
Carbon\Carbon::diffForHumans(Carbon\Carbon $other = NULL, $absolute = false, $short = false) has a new third argument and lack of it in Jenssegers\Date\Date::diffForHumans is not playing nicely.
=> Add third argument to diffForHumans to match Carbon\Carbon

src/Lang/cy.php
Welsh language file was saved with ISO-8859-1 encoding which causes issues in UTF-8 configured projects.
=> Encode Welsh language file with UTF-8

src/DateServiceProvider.php
It's pretty common to have your app change the locale in a middleware. When the app boots up, it's very rare to actually know what the locale will be until the session is booted and locale is set.
This fixes those cases where the locale can be changed at any time after the app has booted.
As a side note, I would recommend to have a proper facade for `Date` because then you can defer loading of the service provider and translator module every request. Anyway that's for another PR.
=> Fix changing locale after app has booted

src/Date.php, tests/DateTest.php
Allows for rapid conversion of plain Carbon objects.
```php
$carbon = Carbon::now();
$date = Date::parse($carbon);
```
L85 also allows Unix timestamps to be passed to `parse()`.
=> Parse Carbon objects

src/Lang/ar.php
In Arabic we don't say (from now :time) we say (:time from now):
Arabic examples:
من الآن 8 أشهر
8 أشهر من الآن 
The line at the very above this one might seem strange that is because Github's website is LTR, not RTL!
I ran into this problem in multiple projects, so please accept this minor change.
BTW:
How can I add another Arabic language? like ar_SY?
In Syria, we call the months by different names! please tell me how can I do so by telling me or sharing a link. thanks in advance
=> Minor change for Arabic translation regarding (from now :time)

src/Lang/sw.php
Just wanted to add Kiswahili version of dates.
For Swahili speakers out there 😃
=> Create Kiswahili / Swahili Version

README.md
It looks like the embed URL of coverage status badge has linked to `http://img.shields.io/coveralls/jenssegers/laravel-date.svg`.
I changed the URL to the newest one that I assumed.
=> Update the embed url of coverage status badge.

tests/TranslationJaTest.php, tests/TranslationTaTest.php
Fix the failing translation tests.
For some reason, `Date::createFromFormat('m', '02')` returns some date in March rather than February.
Fixed by converting that code to `Date::createFromFormat('m-d', '02-02');`
=> Fix failing tests

README.md, src/Lang/ne.php
Notes:
- Month names are transliterated. Wikipedia was used as source.
- Similarly, 'second' and 'minute' are transliterated.
=> Add Nepali (ne) Locale

.travis.yml
- This will allow to check jenssegers/date does not fail with next Carbon release
- This should be paired with daily/weekly CRON job added in the TravisCI panel
=> Add a test for Carbon future release compatibility

src/Date.php, tests/TranslationTest.php
Library offers months declension for formats like `j F Y`. This doesn't work for valid Czech date formatting (`j. F Y` - e. g. _18. prosince 2017_). PR fixes that and allows a month name to be prefixed not only by a space, but a dot as well.
=> Declension detection enhancement.

tests/DateTest.php, tests/TranslationTest.php
This test can fail, because each time you can `Date:now()`, there is no guarantee the timestamp did not change meanwhile.
=> [Unit tests] Use the same timestamp everywhere

README.md
With Laravel 5.5+ the installation steps provided are useless.
=> Mention auto-discovery

composer.json, phpunit.xml, tests/TestCaseBase.php, tests/TranslationKaTest.php
It appears one unit test had the values switched. However I can't verify if it's the code or the test that's wrong.
=> Update dependencies to retain framework compatibility
