jenssegers/date

src/Jenssegers/Date/DateServiceProvider.php

Fixing Laravel 5 checking

---

src/Jenssegers/Date/Date.php

Idea from https://github.com/briannesbitt/Carbon/pull/230

Added optional 2nd parameter to diffForHumans

---

README.md
src/lang/cs/date.php
src/lang/sk/date.php

I added Slovak and Czech translations, both are working properly.

Slovak and czech translations

---

src/lang/cs/date.php

Fixed monday translation

---

README.md
src/lang/uk/date.php

Ukrainian language

---

README.md

The Swedish translations looks fine.

Remove (incomplete) from Swedish.

---

src/Lang/ms.php

Add Malay language for local code of 'ms'

Add Malay language

---

src/Lang/no.php

Quick fix, it's called 'mai' in norwegian.

Fix no.php

---

README.md
src/Lang/hi.php

Added Hindi language, since language is quite complex you have to choose different word for different situation. I have added word that will suit is almost all cases.

Added hindi language

---

README.md

i was looking at the documentation and noticed you dont mention the Laravel Facade capabilities, which made me go back at old code to find that it was possible (as i recalled).
anyway, if for some reason this is a bad idea let me know!

add facade in readme

---

README.md
src/Lang/mk.php

Macedonian language

---

README.md
src/Lang/lv.php

Latvian language support

---

README.md
src/Lang/gl.php

Hi.
Thanks for this great library. Can you merge this pull request, please?

Added galician language

---

README.md
src/Lang/kk.php

Please add Kazakh language. Thank you

Kazakh language support

---

.gitignore
src/Lang/ta.php
tests/TranslationTaTest.php

Adds translations for the language Tamil. All checked by their appropriate tests

Adds translations for Language Tamil

---

tests/TranslationJaTest.php

I added a new test class for Japanese translation test.

Add translation test for Japanese.

---

src/Lang/ko.php

Fix awkward Korean Translation

---

src/DateServiceProvider.php

Similar to https://github.com/jenssegers/date/pull/251/files but without requiring the version check

Bind Laravel LocaleUpdated event

---

src/Lang/hr.php

Update hr.php (Croatian)

---

composer.json
src/Date.php
tests/AutomaticTest.php
tests/DateTest.php
tests/TranslationElTest.php
tests/TranslationHuTest.php
tests/TranslationJaTest.php
tests/TranslationKaTest.php
tests/TranslationTaTest.php
tests/TranslationTest.php
tests/TranslationThTest.php

Provide minimal support of Carbon 2
